// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LivrariaControleEmprestimo.DATA.Models;

[Table("Cliente")]
public partial class Cliente
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("bi")]
    [StringLength(25)]
    [Unicode(false)]
    [DisplayName ("Bi")]
    public string Bi { get; set; }

    [Required]
    [Column("nome")]
    [StringLength(100)]
    [Unicode(false)]
    [DisplayName("Nome")]
    public string Nome { get; set; }

    [Required]
    [Column("endereco")]
    [StringLength(50)]
    [Unicode(false)]
    [DisplayName("Endereço")]
    public string Endereco { get; set; }

    [Required]
    [Column("cidade")]
    [StringLength(50)]
    [Unicode(false)]
    [DisplayName("CIdade")]
    public string Cidade { get; set; }

    [Required]
    [Column("bairro")]
    [StringLength(50)]
    [Unicode(false)]
    [DisplayName("Bairro")]
    public string Bairro { get; set; }

    [Required]
    [Column("numero")]
    [StringLength(50)]
    [Unicode(false)]
    [DisplayName("Numero")]
    public string Numero { get; set; }

    [Column("telefone")]
    [StringLength(50)]
    [Unicode(false)]
    [DisplayName("Telefone")]
    public string Telefone { get; set; }

    [Column("telefoneFixo")]
    [StringLength(50)]
    [Unicode(false)]
    public string TelefoneFixo { get; set; }

    [InverseProperty("IdclienteNavigation")]
    public virtual ICollection<LivroClienteEmprestimo> LivroClienteEmprestimos { get; set; } = new List<LivroClienteEmprestimo>();
}