// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LivrariaControleEmprestimo.DATA.Models;

[Table("Livro")]
public partial class Livro
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("nome")]
    [StringLength(100)]
    [Unicode(false)]
    [DisplayName("Nome")]
    public string Nome { get; set; }

    [Required]
    [Column("autor")]
    [StringLength(100)]
    [Unicode(false)]
    [DisplayName("Autor")]
    public string Autor { get; set; }

    [Required]
    [Column("editora")]
    [StringLength(50)]
    [Unicode(false)]
    [DisplayName("Editora")]
    public string Editora { get; set; }

    [Column("anoPublicacao", TypeName = "datetime")]
    [DisplayName("Ano Publicacao")]
    public DateTime AnoPublicacao { get; set; }

    [Column("edicao")]
    [StringLength(50)]
    [Unicode(false)]
    [DisplayName("Edicao")]
    public string Edicao { get; set; }

    [InverseProperty("IdlivroNavigation")]
    [DisplayName("Emprestimo")]
    public virtual ICollection<LivroClienteEmprestimo> LivroClienteEmprestimos { get; set; } = new List<LivroClienteEmprestimo>();
}