// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LivrariaControleEmprestimo.DATA.Models;


public partial class VwLivroClienteEmprestimo
{
    [Required]
    [Column("bi")]
    [StringLength(25)]
    [Unicode(false)]
    [DisplayName("Bi")]
    public string Bi { get; set; }

    [Required]
    [Column("nome_cliente")]
    [StringLength(100)]
    [Unicode(false)]
    [DisplayName("Nome Cliente")]
    public string NomeCliente { get; set; }

    [Required]
    [Column("nome_livro")]
    [StringLength(100)]
    [Unicode(false)]
    [DisplayName("Nome Livro")]
    public string NomeLivro { get; set; }

    [Column("id")]
    public int Id { get; set; }

    [Column("idlivro")]
    public int? Idlivro { get; set; }

    [Column("idcliente")]
    public int? Idcliente { get; set; }

    [Column("dataEmprestimo", TypeName = "datetime")]
    [DisplayName("Data Emprestimo")]
    public DateTime? DataEmprestimo { get; set; }

    [Column("dataDevolucao", TypeName = "datetime")]
    [DisplayName("Data Devolução")]
    public DateTime? DataDevolucao { get; set; }

    [Column("entregue")]
    [DisplayName("Entregue")]
    public bool Entregue { get; set; }
}